server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: ${DB_USER}
    password: ${Your_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 9D8sK9v2R3kZ7xU8sJ5hL0qP4rT1mC6wX8vL2yN9bT3eV0hR6wA7kJ3zU2bM9fQ
  expiration: 3600000

redis:
  host: localhost
  port: 6379
